frontend:
  container_name: skill_matcher_fe
  image: nginx:alpine
  volumes: 
    - .\app:/usr/share/nginx/html/
  ports:
    - "8888:80"
  environment:
    - NGINX_HOST=skillmatcher.ness
    - NGINX_PORT=8888