node() {
    def app

    stage('Initialize') {
        echo 'Initializing...'
        def node = tool name: 'latest', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        env.PATH = "${node}/bin:${env.PATH}"
        deleteDir()
    }

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        dir('frontend') {
            dir('app') {
                //sh 'npm prune --no-bin-links'
                sh 'npm install' // --no-bin-links'
            }

            app = docker.build("nessfullstackteama/skill_matcher_fe:0.1.${env.BUILD_NUMBER}")
            sh "docker tag nessfullstackteama/skill_matcher_fe:0.1.${env.BUILD_NUMBER} nessfullstackteama/skill_matcher_fe:latest"
        }
    }

    stage('Test image') {
        app.inside {
            sh 'echo OK' //'curl -i http://127.0.0.1/nginx_status'
        }
    }
}