node {
    def app
    env.NODEJS_HOME = "${tool 'Node 10.x'}"
    env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        dir('frontend') {
            dir('app') {
                sh 'npm prune'
                sh 'npm install'
            }

            app = docker.build("nessfullstackteama/skill_matcher_fe:0.1.${env.BUILD_NUMBER}")
            sh "docker tag nessfullstackteama/skill_matcher_fe:0.1.${env.BUILD_NUMBER} nessfullstackteama/skill_matcher_fe:latest"
        }
    }

    stage('Test image') {
        app.inside {
            sh 'echo OK' //'curl -i http://127.0.0.1/nginx_status'
        }
    }
}