node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        dir('database') {
            app = docker.build("nessfullstackteama/skill_matcher_db:0.1.${env.BUILD_NUMBER}")
        }
    }

    stage('Test image') {
        app.inside {
            sh 'mysql -h 127.0.0.1 -u root -pN355Full5t4ck -e"quit"'
        }
    }
}