-- MySQL Script generated by MySQL Workbench
-- Tue Apr 17 20:20:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema skill_matcher
-- -----------------------------------------------------
--DROP SCHEMA IF EXISTS `skill_matcher` ;

-- -----------------------------------------------------
-- Schema skill_matcher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skill_matcher` DEFAULT CHARACTER SET latin1 ;
USE `skill_matcher` ;

-- -----------------------------------------------------
-- Table `skill_matcher`.`Permission`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `skill_matcher`.`Permission` ;

CREATE TABLE IF NOT EXISTS `skill_matcher`.`Permission` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_matcher`.`Skill`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `skill_matcher`.`Skill` ;

CREATE TABLE IF NOT EXISTS `skill_matcher`.`Skill` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `parentId` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `FK_Skill_parentId_id_idx` (`parentId` ASC),
  CONSTRAINT `FK_Skill_parentId_id`
    FOREIGN KEY (`parentId`)
    REFERENCES `skill_matcher`.`Skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_matcher`.`User`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `skill_matcher`.`User` ;

CREATE TABLE IF NOT EXISTS `skill_matcher`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personalNumber` VARCHAR(10) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `personalNumber_UNIQUE` (`personalNumber` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_matcher`.`UserGroup`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `skill_matcher`.`UserGroup` ;

CREATE TABLE IF NOT EXISTS `skill_matcher`.`UserGroup` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_matcher`.`UserGroupPermissions`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `skill_matcher`.`UserGroupPermissions` ;

CREATE TABLE IF NOT EXISTS `skill_matcher`.`UserGroupPermissions` (
  `userGroupId` INT(11) NOT NULL,
  `permissionId` INT(11) NOT NULL,
  PRIMARY KEY (`userGroupId`, `permissionId`),
  INDEX `FK_UserGroupPermissions_permissionId_Permission_id_idx` (`permissionId` ASC),
  CONSTRAINT `FK_UserGroupPermissions_permissionId_Permission_id`
    FOREIGN KEY (`permissionId`)
    REFERENCES `skill_matcher`.`Permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserGroupPermissions_userGroupId_UserGroup_id`
    FOREIGN KEY (`userGroupId`)
    REFERENCES `skill_matcher`.`UserGroup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_matcher`.`UserSkills`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `skill_matcher`.`UserSkills` ;

CREATE TABLE IF NOT EXISTS `skill_matcher`.`UserSkills` (
  `userId` INT(11) NOT NULL,
  `skillId` INT(11) NOT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `experience` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`, `skillId`),
  UNIQUE INDEX `UK_UserSkills_userId_skillId` (`userId` ASC, `skillId` ASC),
  INDEX `FK_UserSkills_skillId _Skill_id_idx` (`skillId` ASC),
  CONSTRAINT `FK_UserSkills_skillId _Skill_id`
    FOREIGN KEY (`skillId`)
    REFERENCES `skill_matcher`.`Skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserSkills_userId_User_id`
    FOREIGN KEY (`userId`)
    REFERENCES `skill_matcher`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_matcher`.`UserUserGroups`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `skill_matcher`.`UserUserGroups` ;

CREATE TABLE IF NOT EXISTS `skill_matcher`.`UserUserGroups` (
  `userId` INT(11) NOT NULL,
  `userGroupId` INT(11) NOT NULL,
  PRIMARY KEY (`userId`, `userGroupId`),
  UNIQUE INDEX `UK_UserUserGroups_userId_userGroupId` (`userId` ASC, `userGroupId` ASC),
  INDEX `FK_UserUserGroups_userGroupId_UserGroup_id_idx` (`userGroupId` ASC),
  INDEX `FK_UserUserGroups_userId_User_id_idx` (`userId` ASC),
  CONSTRAINT `FK_UserUserGroups_userGroupId_UserGroup_id`
    FOREIGN KEY (`userGroupId`)
    REFERENCES `skill_matcher`.`UserGroup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserUserGroups_userId_User_id`
    FOREIGN KEY (`userId`)
    REFERENCES `skill_matcher`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
